package it.indra.SigecAPI.migration.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.SigecAPI.migration.entity.Sigea2Vip1ShotMigra;

/**
* Generated by Spring Data Generator on 11/05/2020
*/
@Repository
public interface Sigea2Vip1ShotMigraRepository extends JpaRepository<Sigea2Vip1ShotMigra, Long>{

	List<Sigea2Vip1ShotMigra> findByidVipBetweenAndRelated(Long start, Long end, long l);

}
