package it.indra.sigea2vip.persistence.repository;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.AccessibilitamappingEntity;


/**
* Generated by Spring Data Generator on 11/05/2020
*/
@Repository
public interface AccessibilitamappingEntityRepository extends JpaRepository<AccessibilitamappingEntity, Long>{

	Long deleteByIdevento(Long idEventoVip);

	List<AccessibilitamappingEntity> findAllByIdevento(Long idEventoVip);

	List<AccessibilitamappingEntity> findAllByIdattivita(Long idAttivita);

}
