package it.indra.sigea2vip.persistence.repository;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.AccessibilitadisabilitaEntity;

/**
* Generated by Spring Data Generator on 22/07/2020
*/
@Repository
public interface AccessibilitadisabilitaEntityRepository extends JpaRepository<AccessibilitadisabilitaEntity, Long> {

	@Modifying
	@Query("delete from AccessibilitadisabilitaEntity b where b.idmapping=?1")
	void deleteByIdmapping(@Param("idmapping") long idmapping);

	public Set<AccessibilitadisabilitaEntity> findByIdmapping(long idMapping);

}
