package it.indra.sigea2vip.persistence.repository;

import java.sql.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.AttivitaturisticaEntity;

/**
* Generated by Spring Data Generator on 22/05/2020
*/
@Repository
public interface AttivitaturisticaEntityRepository extends JpaRepository<AttivitaturisticaEntity, Long>{

	List<AttivitaturisticaEntity> findBydataaggiornamentoBetweenAndIdstato(Date dataInizio, Date dataFine,
			String statoPubblic);

}
