package it.indra.sigea2vip.persistence.repository;


import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.AttivitaanagraficaEntity;

/**
* Generated by Spring Data Generator on 22/05/2020
*/
@Repository
public interface AttivitaanagraficaEntityRepository extends JpaRepository<AttivitaanagraficaEntity, Long>{

}
