package it.indra.sigea2vip.persistence.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.AttivitamediaEntity;

/**
* Generated by Spring Data Generator on 22/05/2020
*/
@Repository
public interface AttivitamediaEntityRepository extends JpaRepository<AttivitamediaEntity, Long>{

	public List<AttivitamediaEntity> findByIdAttivita(Long idAttivita);

	public Long deleteByIdAttivita(Long idAttivita);


}
