package it.indra.sigea2vip.persistence.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.BackeventiutentiEntity;

/**
* Generated by Spring Data Generator on 20/07/2020
*/
@Repository
public interface BackeventiutentiEntityRepository extends JpaRepository<BackeventiutentiEntity, Long>{

	public BackeventiutentiEntity findByEmail(String email);
	public BackeventiutentiEntity findByUsername(String username);
	public BackeventiutentiEntity findByIdutente(Long idutenteinserimento);
	public BackeventiutentiEntity findByEmailOrUsername(String lowerCase, String username);

}
