package it.indra.sigea2vip.persistence.repository;

import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.EventoattrattorimappingEntity;

/**
* Generated by Spring Data Generator on 20/07/2020
*/
@Repository
public interface EventoattrattorimappingEntityRepository extends JpaRepository<EventoattrattorimappingEntity, Long> {

	public long deleteByIdevento(long idvip);

	public Set<EventoattrattorimappingEntity> findAllByIdevento(long idEvento);

}
