package it.indra.sigea2vip.persistence.repository;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.EventoallegatiEntity;

/**
* Generated by Spring Data Generator on 20/05/2020
*/
@Repository
public interface EventoallegatiEntityRepository extends JpaRepository<EventoallegatiEntity, Long>{

	public List<EventoallegatiEntity> findByIdref(Long idref);
	public long deleteByIdref(long idref);

}
