package it.indra.sigea2vip.persistence.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.EventomicroesperienzemappingEntity;

/**
* Generated by Spring Data Generator on 21/07/2020
*/
@Repository
public interface EventomicroesperienzemappingEntityRepository extends JpaRepository<EventomicroesperienzemappingEntity, Long>{

	@Modifying
	@Query("delete from EventomicroesperienzemappingEntity b where b.idevento=?1")
	void deleteByIdEvento(@Param("idevento") long idevento);

	List<EventomicroesperienzemappingEntity> findByIdevento(long idEvento);


}
