package it.indra.sigea2vip.persistence.repository;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.EventolocationEntity;

/**
 * Generated by Spring Data Generator on 13/05/2020
 */
@Repository
public interface EventolocationEntityRepository extends JpaRepository<EventolocationEntity, Long> {

	Set<EventolocationEntity> findAllByIdevento(long idEvento);

}
