package it.indra.sigea2vip.persistence.repository;

import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.EventoallegatiintEntity;

/**
* Generated by Spring Data Generator on 20/05/2020
*/
@Repository
public interface EventoallegatiintEntityRepository extends JpaRepository<EventoallegatiintEntity, Long> {

		public int deleteByIdallegatoAndIdlingua(long idevento,String idLingua);

		public Set<EventoallegatiintEntity> findByIdallegato(long idallegato);

}
