package it.indra.sigea2vip.persistence.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.FotointEntity;

/**
* Generated by Spring Data Generator on 26/05/2020
*/
@Repository
public interface FotointEntityRepository extends JpaRepository<FotointEntity, String> {

}
