package it.indra.sigea2vip.persistence.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.GiornoaperturaEntity;

/**
* Generated by Spring Data Generator on 21/07/2020
*/
@Repository
public interface GiornoaperturaEntityRepository extends JpaRepository<GiornoaperturaEntity, Long>{

	long deleteByIdorario(long idOrario);


}
