package it.indra.sigea2vip.persistence.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.MicroesperienzaintEntity;

/**
* Generated by Spring Data Generator on 22/07/2020
*/
@Repository
public interface MicroesperienzaintEntityRepository extends JpaRepository<MicroesperienzaintEntity, String> {

	public MicroesperienzaintEntity findByIdmicroesperienza(String idMicroesperienza);
}
