package it.indra.sigea2vip.persistence.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.Sigea2VipEntity;

/**
* Generated by Spring Data Generator on 11/05/2020
*/
@Repository
public interface Sigea2VipEntityRepository extends JpaRepository<Sigea2VipEntity, Long>{

	Sigea2VipEntity findByIdEventoVip(Long idEvento);

	Sigea2VipEntity deleteByIdSigea(Long eventoid);

	Sigea2VipEntity findByIdAttivitaVip(Long id);

	Sigea2VipEntity findByIdSigea(Long eventoId);

	

}
