package it.indra.sigea2vip.persistence.repository;

import java.util.List;
import java.util.Set;

import javax.persistence.LockModeType;
import javax.persistence.QueryHint;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Lock;
import org.springframework.data.jpa.repository.QueryHints;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import it.indra.sigea2vip.persistence.entity.TicketmappingEntity;

/**
* Generated by Spring Data Generator on 11/05/2020
*/
@Repository
public interface TicketmappingEntityRepository extends JpaRepository<TicketmappingEntity, Long>{

	@Lock(LockModeType.PESSIMISTIC_READ)
	@QueryHints({@QueryHint(name = "javax.persistence.lock.timeout", value = "3000")})
	public List<TicketmappingEntity> findAllByIdevento(Long idEventoVip);

	@Lock(LockModeType.PESSIMISTIC_READ)
	@QueryHints({@QueryHint(name = "javax.persistence.lock.timeout", value = "3000")})
	public List<TicketmappingEntity> findAllByIdattivita(Long idAttivita);

	public Set<TicketmappingEntity> findByIdevento(Long idEvento);


}
