package it.indra.sigea2vip.persistence.repository;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.indra.sigea2vip.persistence.entity.TicketnoteintEntity;

/**
* Generated by Spring Data Generator on 11/05/2020
*/
@Repository
public interface TicketnoteintEntityRepository extends JpaRepository<TicketnoteintEntity, Long>{

	Long deleteByIdticketAndIdlingua(long idticket, String linguaEvento);

	Set<TicketnoteintEntity> findAllByIdticket(long idticket);

}
