apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sigec
  namespace: dev-sigea-backend
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-nfs   
