apiVersion: v1
kind: Service
metadata:
  name: sigec-svc
spec:
  type: ClusterIP
  ports:
  - name: sigec
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: sigec-api
    module: api