INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagGratisAnziani','Anziani');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagGratisBambini','Bambini');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagGratisConvenzioni','Convenzioni gratuite attive');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagGratisDisabili','Disabili');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagGratisAccompagnatori','Accompagnatori disabili');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagRidottoAnziani','Anziani');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagRidottoBambini','Bambini');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagRidottoConvenzioni','Convenzioni ridotte attive');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagRidottoDisabili','Disabili');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Ticket.flagRidottoAccompagnatori','Accompagnatori disabili');

INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagFamiglieBambini','Famiglie con bambini');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagPersoneAnimali','Persone con animali');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagDisabilitaFisica','Disabilit&agrave fisica');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagDisabilitaVisiva','Disabilit&agrave visiva');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagDisabilitaUditiva','Disabilit&agrave uditiva');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagGravidanza','Donne in stato di gravidanza');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagAnziani','Anziani');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagCaniMedi','Cani taglia media');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagCaniPiccoli','Cani taglia piccola');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagCani','Tutti i cani');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagBiblioteca','Biblioteca per bambini');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagGiardini','Spazi esterni attrezzati (giardini)');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagLudoteca','Ludoteca');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagNursey','Nursey');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagParcogiochi','Parco giochi');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagPercorsi','Percorsi accessibili');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagSito','Sito web accessibile');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagInfopoint','Punto informazioni/accoglienza accessibile');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagServiziIgienici','Servizi igienici accessibili');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagParcheggioDisabili','Parcheggio riservato alle persone con disabilit&agrave');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagIngressi','Ingresso principale o secondario accessibile (pedana, ascensore, altro)');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagPercorsiTattili','Percorsi tattili');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagGuideBraille','Guide cartacee in braille');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagSegnaleticaBraille','Segnaletica in braille');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagSegnaleticaLeggibile','Segnaletica ad altro contrasto/alta leggibilit&agrave');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagMaterialeLeggibile','Materiale informativo ad altro contrasto/alta leggibilit&agrave');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagPostazioniAudio','Postazioni audio-descrittive della struttura e del percorso');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagAudioguide','Audioguide per persone ipovedenti o non vedenti');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagAudioguidePercorsi','Audioguide con percorsi tattili per persone ipovedenti o non vedenti');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagMaterialeSottotitolato','Materiale audiovisivo sottotitolato');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagRiproduzioneTattili','Riproduzione tattili');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagComputer','Computer con descrizione vocali');
INSERT INTO sigec.t_sigea_decodifica ("key",value) VALUES ('Accessibilita.flagLis','Personale che conosce la Lingua dei Segni Italiana (LIS)');