ALTER TABLE sigec.t_sigea_datigenerali ALTER COLUMN DESCRIZIONE TYPE TEXT;
ALTER TABLE sigec.t_sigea_datigenerali ALTER COLUMN ABSTRACT TYPE TEXT;

ALTER TABLE sigec.t_sigea_tickets ALTER COLUMN NOTA TYPE TEXT;