UPDATE TURISMO.EVENTOINT E
SET DESCRIZIONE=REPLACE(DESCRIZIONE,'¿','''')
WHERE E.IDEVENTO IN
(SELECT IDEVENTO_VIP 
FROM TURISMO.SIGEA2VIP SV 
WHERE SV.DATAINSERIMENTO > SYSDATE-28
AND IDEVENTO_VIP IS NOT NULL);

UPDATE TURISMO.EVENTOINT E
SET NOME=REPLACE(NOME,'¿','''')
WHERE E.IDEVENTO IN
(SELECT IDEVENTO_VIP 
FROM TURISMO.SIGEA2VIP SV 
WHERE SV.DATAINSERIMENTO > SYSDATE-28
AND IDEVENTO_VIP IS NOT NULL);

UPDATE TURISMO.EVENTOINT E
SET ABSTRACT=REPLACE(ABSTRACT,'¿','''')
WHERE E.IDEVENTO IN
(SELECT IDEVENTO_VIP 
FROM TURISMO.SIGEA2VIP SV 
WHERE SV.DATAINSERIMENTO > SYSDATE-28
AND IDEVENTO_VIP IS NOT NULL);