ALTER TABLE sigec.t_sigea_logeventi 
ADD COLUMN denominazione_attivita varchar(100);

UPDATE SIGEC.T_SIGEA_LOGEVENTI LE
SET DENOMINAZIONE_ATTIVITA ='ARET Direzione - Comunicazione'
WHERE
	LE.NOME_UTENTE LIKE '%Chiarullo%'
OR 	LE.NOME_UTENTE LIKE '%Bosna%'
--OR LE.NOME_UTENTE LIKE '%Bronzino%'
OR 	LE.NOME_UTENTE LIKE '%Biagio Mastrangelo%'
OR 	LE.NOME_UTENTE LIKE '%CRIVELLI%'
OR 	LE.NOME_UTENTE LIKE '%GIUSY BARLETTA%'
OR 	LE.NOME_UTENTE LIKE '%Rita Malerba%'
OR 	LE.NOME_UTENTE LIKE '%GIORGIO GUARINI%';


--LANCIARE SE E SOLO SE LANCIATO L'UPDATE PRECEDENTE
UPDATE SIGEC.T_SIGEA_LOGEVENTI LE
SET DENOMINAZIONE_ATTIVITA =
(   SELECT DISTINCT SA.DENOMINAZIONE
	FROM SIGEC.T_SIGEA_EVENTI SE, 
		 SIGEC.T_SIGEA_ATTIVITA SA 
	WHERE LE.EVENTO_ID=SE.EVENTO_ID
	AND SE.ATTIVITA_ID=SA.ATTIVITA_ID
	)
WHERE 
	DENOMINAZIONE_ATTIVITA is null;

--LANCIARE SE E SOLO SE LANCIATO L UPDATE PRECEDENTE
UPDATE SIGEC.T_SIGEA_LOGEVENTI LE
SET DENOMINAZIONE_ATTIVITA =
(   SELECT DISTINCT SA.DENOMINAZIONE
	FROM SIGEC.T_SIGEA_EVENTI SE, 
		 SIGEC.T_SIGEA_RICHIESTAATTIVITA SA 
	WHERE LE.EVENTO_ID=SE.EVENTO_ID
	AND SE.RICHIESTA_ID=SA.RICHIESTA_ID
	)
WHERE 
	DENOMINAZIONE_ATTIVITA is null;

--L'UPDATE DEVE ESSERE SU 0 RIGHE
UPDATE SIGEC.T_SIGEA_LOGEVENTI LE
SET DENOMINAZIONE_ATTIVITA = 'N/A'
WHERE
	DENOMINAZIONE_ATTIVITA is null

/*
QUERY AUSILIO

SELECT DISTINCT SA.DENOMINAZIONE--223
FROM SIGEC.T_SIGEA_LOGEVENTI LE JOIN SIGEC.T_SIGEA_EVENTI SE ON LE.EVENTO_ID=SE.EVENTO_ID
 join SIGEC.T_SIGEA_ATTIVITA SA ON SE.ATTIVITA_ID=SA.ATTIVITA_ID
WHERE 1=1
and LE.NOME_UTENTE not LIKE '%Chiarullo%'
AND LE.NOME_UTENTE not LIKE '%Bosna%'
AND LE.NOME_UTENTE not LIKE '%Mastrangelo%'
AND LE.NOME_UTENTE not LIKE '%CRIVELLI%'
AND LE.NOME_UTENTE not LIKE '%BARLETTA%'
AND LE.NOME_UTENTE not LIKE '%Malerba%'
AND LE.NOME_UTENTE not LIKE '%GUARINI%'
UNION
SELECT DISTINCT SA.DENOMINAZIONE--223
FROM SIGEC.T_SIGEA_LOGEVENTI LE JOIN SIGEC.T_SIGEA_EVENTI SE ON LE.EVENTO_ID=SE.EVENTO_ID
 join SIGEC.T_SIGEA_RICHIESTAATTIVITA SA ON SE.RICHIESTA_ID=SA.RICHIESTA_ID
WHERE 1=1
and LE.NOME_UTENTE not LIKE '%Chiarullo%'
AND LE.NOME_UTENTE not LIKE '%Bosna%'
--OR AA.NOME_UTENTE LIKE '%Bronzino%'
AND LE.NOME_UTENTE not LIKE '%Mastrangelo%'
AND LE.NOME_UTENTE not LIKE '%CRIVELLI%'
AND LE.NOME_UTENTE not LIKE '%BARLETTA%'
AND LE.NOME_UTENTE not LIKE '%Malerba%'
AND LE.NOME_UTENTE not LIKE '%GUARINI%'

*/


/*COLLAUDO

UPDATE SIGEC.T_SIGEA_LOGEVENTI LE
SET DENOMINAZIONE_ATTIVITA ='ARET Direzione - Comunicazione'
WHERE 
	LE.NOME_UTENTE LIKE '%Battaglia%'
OR 	LE.NOME_UTENTE LIKE '%Rossi%'
OR 	LE.NOME_UTENTE LIKE '%Vocino%'
OR 	LE.NOME_UTENTE LIKE '%Malerba%'
OR 	LE.NOME_UTENTE LIKE '%Parente%'
OR 	LE.NOME_UTENTE LIKE '%Benedetto%'
OR 	LE.NOME_UTENTE LIKE '%Guglielmi%'
OR 	LE.NOME_UTENTE LIKE '%Intini%'
OR 	LE.NOME_UTENTE LIKE '%Mastrangelo%'
OR 	LE.NOME_UTENTE LIKE '%test%'
OR 	LE.NOME_UTENTE LIKE '%Bonaparte%'
OR 	LE.NOME_UTENTE LIKE '%Recchia%'
OR 	LE.NOME_UTENTE LIKE '%Mazza%'
OR 	LE.NOME_UTENTE LIKE '%Reda%'
OR 	LE.NOME_UTENTE LIKE '%Bixio%';

--LANCIARE SE E SOLO SE LANCIATO L'UPDATE PRECEDENTE
UPDATE SIGEC.T_SIGEA_LOGEVENTI LE
SET DENOMINAZIONE_ATTIVITA =
(   SELECT DISTINCT SA.DENOMINAZIONE
	FROM SIGEC.T_SIGEA_EVENTI SE, 
		 SIGEC.T_SIGEA_ATTIVITA SA 
	WHERE LE.EVENTO_ID=SE.EVENTO_ID
	AND SE.ATTIVITA_ID=SA.ATTIVITA_ID
	)
WHERE 
	DENOMINAZIONE_ATTIVITA is null;

--LANCIARE SE E SOLO SE LANCIATO L'UPDATE PRECEDENTE
UPDATE SIGEC.T_SIGEA_LOGEVENTI LE
SET DENOMINAZIONE_ATTIVITA =
(   SELECT DISTINCT SA.DENOMINAZIONE--223
	FROM SIGEC.T_SIGEA_EVENTI SE, 
		 SIGEC.T_SIGEA_RICHIESTAATTIVITA SA 
	WHERE LE.EVENTO_ID=SE.EVENTO_ID
	AND SE.RICHIESTA_ID=SA.RICHIESTA_ID
	)
WHERE 
	DENOMINAZIONE_ATTIVITA is null;

--L'UPDATE DEVE ESSERE SU 0 RIGHE
UPDATE SIGEC.T_SIGEA_LOGEVENTI LE
SET DENOMINAZIONE_ATTIVITA = 'N/A'
WHERE
	DENOMINAZIONE_ATTIVITA is null

*/

