ALTER TABLE TURISMO.ATTIVITATURISTICAINT MODIFY DENOMINAZIONE VARCHAR2(500);
ALTER TABLE TURISMO.ATTIVITATURISTICAINT MODIFY ABSTRACT VARCHAR2(1500);
ALTER TABLE TURISMO.ATTIVITATURISTICAINT MODIFY DESCRIZIONE VARCHAR2(4000);