INSERT INTO DMS.ENTITA_SERVIZI (ID_ENTITA, ID_SERVIZIO) VALUES ('31949', '72');
INSERT INTO DMS.ENTITA_SERVIZI (ID_ENTITA, ID_SERVIZIO) VALUES ('31949', '50');
INSERT INTO DMS.ENTITA_SERVIZI (ID_ENTITA, ID_SERVIZIO) VALUES ('31949', '48');
