--DROP TABLE SIGEC.T_SIGEA_SIGEA2VIP1SHOT_MIGRA;
CREATE TABLE SIGEC.T_SIGEA_SIGEA2VIP1SHOT_MIGRA
AS 			 
	SELECT ID_SIGEA, 
		   IDEVENTO_VIP ID_VIP,
	'CONTENUTO' AS CONT,
	'RASSEGNA' TIPO,
	(SELECT ID_SIGEA FROM SIGEC.T_SIGEA_SIGEA2VIP_MIGRA S WHERE S.IDEVENTO_VIP=IDRASSEGNA) ID_SIGEA_2, 
	0 AS RELATED 
	FROM SIGEC.T_SIGEA_SIGEA2VIP_MIGRA E, SIGEC.T_SIGEA_RASSEGNAEVENTIMAPPING_MIGRA R 
	WHERE E.IDEVENTO_VIP=R.IDEVENTO
UNION 
	SELECT ID_SIGEA, 
		   IDEVENTO_VIP ID_VIP,
	'CONTIENE' AS CONT,
	'EVENTO' TIPO,
	(SELECT ID_SIGEA FROM SIGEC.T_SIGEA_SIGEA2VIP_MIGRA S WHERE S.IDEVENTO_VIP=IDEVENTO) ID_SIGEA_2 ,
	0 AS RELATED 
	FROM SIGEC.T_SIGEA_SIGEA2VIP_MIGRA E, SIGEC.T_SIGEA_RASSEGNAEVENTIMAPPING_MIGRA R 
	WHERE E.IDEVENTO_VIP=R.IDRASSEGNA 


/* DA LANCIARE OGNI QUALVOLTA SI VUOLE UTILIZZARE IL SERVIZIO /related IN COLLAUDO
	SE SI FA UN 1SHOT NON è NECESSARIO!!!!

UPDATE SIGEC.T_SIGEA_SIGEA2VIP1SHOT_MIGRA 
SET RELATED = 1;

INSERT INTO SIGEC.T_SIGEA_SIGEA2VIP1SHOT_MIGRA
SELECT ID_SIGEA,ID_VIP,CONT,TIPO,ID_SIGEA_2, 0 AS RELATED
FROM (
SELECT ID_SIGEA, 
	IDEVENTO_VIP ID_VIP,
	'CONTENUTO' AS CONT,
	'RASSEGNA' TIPO,
	(SELECT ID_SIGEA FROM SIGEC.T_SIGEA_SIGEA2VIP_MIGRA S WHERE S.IDEVENTO_VIP=IDRASSEGNA) ID_SIGEA_2
	FROM SIGEC.T_SIGEA_SIGEA2VIP_MIGRA E, SIGEC.T_SIGEA_RASSEGNAEVENTIMAPPING_MIGRA R 
	WHERE E.IDEVENTO_VIP=R.IDEVENTO
UNION 
	SELECT ID_SIGEA, 
	IDEVENTO_VIP ID_VIP,
	'CONTIENE' AS CONT,
	'EVENTO' TIPO,
	(SELECT ID_SIGEA FROM SIGEC.T_SIGEA_SIGEA2VIP_MIGRA S WHERE S.IDEVENTO_VIP=IDEVENTO) ID_SIGEA_2
	FROM SIGEC.T_SIGEA_SIGEA2VIP_MIGRA E, SIGEC.T_SIGEA_RASSEGNAEVENTIMAPPING_MIGRA R 
	WHERE E.IDEVENTO_VIP=R.IDRASSEGNA
)A
EXCEPT 
SELECT ID_SIGEA,ID_VIP,CONT,TIPO,ID_SIGEA_2, 0
FROM SIGEC.T_SIGEA_SIGEA2VIP1SHOT_MIGRA B

*/