  CREATE TABLE TURISMO.SIGEA2VIP
   (	"ID_SIGEA" NUMBER(38,0) NOT NULL ENABLE, 
	"IDEVENTO_VIP" NUMBER(38,0), 
	"DATAINSERIMENTO" DATE, 
	"IDATTIVITA_VIP" NUMBER(38,0), 
	 CONSTRAINT "SIGEA2VIP_PK" PRIMARY KEY ("ID_SIGEA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TURISMO_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TURISMO_DATA" ;