
/*	query per verifiche rapide su vip
SELECT DISTINCT EA.*
FROM (SELECT * FROM TURISMO.EVENTO WHERE IDSTATOAPPROVAZIONE=1 AND TIPOLOGIA IS NOT NULL) E
--,TURISMO.TICKETMAPPING TM, TURISMO.TICKET T ,TURISMO.TICKETNOTEINT TN, TURISMO.TICKETSCONTO TS,TURISMO.SCONTO S
--,TURISMO.ACCESSIBILITAMAPPING AM,TURISMO.ACCESSIBILITAANIMALE AA, TURISMO.ACCESSIBILITADISABILITA AD, TURISMO.ACCESSIBILITASERVIZIO ASS, TURISMO.ACCESSIBILITASPAZIOBAMBINI AB
--,TURISMO.EVENTOINT EI 
--,TURISMO.EVENTOLOCATION EL, TURISMO.EVENTOATTRATTORIMAPPING EAM, TURISMO.ATTRATTOREINT AI
--,TURISMO.EVENTOORARIO EO, TURISMO.ORARIO O, TURISMO.GIORNOCHIUSURA GC 
--,TURISMO.EVENTOALLEGATI EA, TURISMO.EVENTOALLEGATIINT EAI
--,TURISMO.RASSEGNAEVENTIMAPPING REM
--,TURISMO.EVENTOCATEGORIAMAPPING ECM
--,TURISMO.CATEGORIAEVENTO CE
--,TURISMO.EVENTOMICROESPERIENZEMAPPING EMM
WHERE IDSTATOAPPROVAZIONE=1 
AND E.TIPOLOGIA IS NOT NULL 
--AND E.IDEVENTO=TM.IDEVENTO 
--AND TM.IDTICKET=T.IDTICKET
--AND TM.IDTICKET=TN.IDTICKET
--AND TM.IDTICKET=TS.IDTICKET
--AND S.IDSCONTO =TS.IDSCONTO 
--AND AM.IDEVENTO =E.IDEVENTO 
--AND AM.ID=AA.IDMAPPING 
--AND AM.ID=AD.IDMAPPING 
--AND AM.ID=ASS.IDMAPPING 
---AND AM.ID=AB.IDMAPPING
--AND EI.IDEVENTO =E.IDEVENTO 
--AND EL.IDEVENTO =E.IDEVENTO
--AND EAM.IDEVENTO =E.IDEVENTO
--AND AI.IDATTRATTORE =EAM.IDATTRATTORE 
--AND EO.IDEVENTO =E.IDEVENTO 
--AND O.IDORARIO =EO.IDORARIO 
--AND GC.IDORARIO =EO.IDORARIO
--AND EA.IDREF =E.IDEVENTO 
--AND EA.IDALLEGATO = EAI.IDALLEGATO 
--AND (REM.IDEVENTO =E.IDEVENTO OR REM.IDRASSEGNA =E.IDEVENTO)
--AND ECM.IDEVENTO =E.IDEVENTO 
--AND (CE.IDCATEGORIA = ECM.IDCATEGORIA OR CE.IDPARENT =ECM.IDCATEGORIA)
--AND EMM.IDEVENTO =E.IDEVENTO 
*/