openapi: 3.0.0
info:
  title: BandiAPI
  description: "BandiAPI è la componente wrapper dell'Ecosistema Turismo-Cultura che interagisce con il servizio esterno di monitoraggio bandi e progetti"
  version: v1
servers:
  - url: ND
    description: SVILUPPO
  - url: ND
    description: COLLAUDO
  - url: ND
    description: PRODUZIONE
tags:
  - name: Bandi
  - name: Progetti
paths:
  /bandi:
    get:
      tags:
        - Bandi
      summary: Restituisce i dati dei bandi recuperati dal servizio esterno di monitoraggio
      operationId: getBandi
      responses:
        "200":
          description: Json contenente una lista in cui viene esplicitato il dettaglio di uno o più bandi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProgettiDTO"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "404":
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500InternalServerError"
        "503":
          $ref: "#/components/responses/503ServiceUnavailable"
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
  /progetti:
    get:
      tags:
        - Progetti
      summary: Restituisce i dati dei progetti recuperati dal servizio esterno di monitoraggio
      operationId: getProgetti
      parameters:
        - name: codice_fiscale
          in: query
          required: true
          description: codice fiscale associato al progetto
          schema:
            type: string
      responses:
        "200":
          description: Json contenente una lista in cui viene esplicitato il dettaglio di uno o più progetti
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BandiDTO"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "404":
          $ref: "#/components/responses/404NotFound"
        "500":
          $ref: "#/components/responses/500InternalServerError"
        "503":
          $ref: "#/components/responses/503ServiceUnavailable"
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
components:
  schemas:
    Problem:
      properties:
        detail:
          description: "A human readable explanation specific to this occurrence of the\nproblem. You MUST NOT expose internal informations, personal\ndata or implementation details through this field.\n"
          type: string
        instance:
          description: "An absolute URI that identifies the specific occurrence of the problem.\nIt may or may not yield further information if dereferenced.\n"
          format: uri
          type: string
        status:
          description: "The HTTP status code generated by the origin server for this occurrence\nof the problem.\n"
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: "A short, summary of the problem type. Written in english and readable\nfor engineers (usually not suited for non technical stakeholders and\nnot localized); example: Service Unavailable\n"
          type: string
        type:
          default: "about:blank"
          description: "An absolute URI that identifies the problem type.  When dereferenced,\nit SHOULD provide human-readable documentation for the problem type\n(e.g., using HTML).\n"
          format: uri
          type: string
      type: object
    BandiDTO:
      properties:
        items:
          description: Lista dei bandi
          type: array
          items:
            $ref: "#/components/schemas/BandoDTO"
      type: object
    ProgettoDTO:
      properties:
        id_bando:
          description: Id del bando
          type: string
        nome_bando:
          description: Nome del bando
          type: string
        id_progetto:
          description: Id del progetto
          type: string
        titolo_progetto:
          description: Titolo progetto
          type: string
        id_impresa:
          description: "Id dell'impresa"
          type: string
        codice_fiscale:
          description: Codice fiscale
          type: string
        denominazione:
          description: Denominazione
          type: string
        forma_partecipazione:
          description: Modalità di partecipazione
          type: string
      type: object
    ProgettiDTO:
      properties:
        items:
          description: Lista dei progetti
          type: array
          items:
            $ref: "#/components/schemas/ProgettoDTO"
      type: object
    BandoDTO:
      properties:
        id_bando:
          description: Id del bando
          type: string
        nome_bando:
          description: Nome del bando
          type: string
      type: object
  responses:
    400BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
      description: Bad Request
    404NotFound:
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
      description: Not Found
    429TooManyRequests:
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
      description: Too many requests
      headers:
        Retry-After:
          $ref: "#/components/headers/Retry-After"
        X-RateLimit-Limit:
          $ref: "#/components/headers/X-RateLimit-Limit"
        X-RateLimit-Remaining:
          $ref: "#/components/headers/X-RateLimit-Remaining"
        X-RateLimit-Reset:
          $ref: "#/components/headers/X-RateLimit-Reset"
    500InternalServerError:
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
      description: Service Unavailable
      headers:
        Retry-After:
          $ref: "#/components/headers/Retry-After"
    503ServiceUnavailable:
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
      description: Service Unavailable
      headers:
        Retry-After:
          $ref: "#/components/headers/Retry-After"
    401Unauthorized:
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
      description: Unauthorized
    default:
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
      description: Unexpected error
  headers:
    Retry-After:
      description: "Retry contacting the endpoint *at least* after seconds.\nSee https://tools.ietf.org/html/rfc7231#section-7.1.3"
      schema:
        format: int32
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        type: integer
